name: Windows EXE Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller exifread pillow geopy

      - name: Build EXE
        run: pyinstaller --onefile potto_grid_android.py

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: potto_grid_android.exe
          path: dist/potto_grid_android.exe
